NCBIClient (from internal)
virtool/virtool-cli pull request #116
Opened 2024-03-12 21:48 UTC by sygao

- Add `virtool_cli.ncbi.NCBIClient` and `virtool_cli.ncbi.NCBICache`
	- Add `NCBIClient.fetch_accessions()`,  `NCBIClient.fetch_taxonomy()`
		- fetches and parses in a single method
		- caches data if flag is set
	- Add `NCBIClient.link_accessions_to_taxid()` for use in update functions
	- Add corresponding tests in `test_ncbi_client` and `test_ncbi_cache`
		- run `pytest tests/test_ncbi_client.py -m "not ncbi"` to run NCBI database-free tests
- Add Pydantic validation in `virtool_cli.ncbi.models`

2024-03-15 18:11 UTC, igboyes requested changes
* The biggest thing that needs to be fixed here is handling the flaky `400` errors. Reading the response will give a clue as to the reason if you haven't tried it.
  ```py
  except HTTPError as e:
    print(e.read())
  ```
* It seems to me that _genbank_ and _nuccore_ are being used somewhat interchangeably. I think it would be best to use _genbank_ as it will be more familiar to biologists. The only thing that needs to stay `nuccore` is variant in the database enum. Thoughts?
* If you are still having problems with the `NCBI_` environmental variables not getting into the tests, moving the `get` and setting of the `Entrez` attributes to `virtool_cli/__init__.py` should fix the problem. I don't think the code is imported where it is now during testing and thus is not being executed.

2024-03-15 18:11 UTC, igboyes commented on tests/test_ncbi_client.py
> +    async def test_fetch_raw_via_accessions(self, accessions):
```suggestion
    async def test_fetch_raw_via_accessions(self, accessions: list[str]):
```

2024-03-15 23:07 UTC, sygao commented on tests/test_ncbi_cache.py
> +        pytest.fail(f"Cache scratch path was not set up correctly: {exc}")
This part of the test only needs to make sure the cache directories have JSON files in them. I don't need to actually do anything with the contents, so this seems more efficient than turning the generator into a list.

2024-03-18 22:17 UTC, sygao commented on tests/test_ncbi_client.py
> +            pytest.fail("Could not retrieve any records from cache")
Can't be sure if there isn't any sort of system chaff in there unless the environment is 100% fresh. Checking only the relevant filetype is the cleanest way to ignore system chaff.

2024-03-18 23:36 UTC, sygao commented on tests/test_ncbi_client.py
> +    assert taxon_name.lower() == expected.lower()
== has case insensitivity. I'll just modify the input data for now.

2024-03-20 18:53 UTC, igboyes approved these changes

2024-03-20 18:53 UTC, igboyes commented on tests/test_ncbi_cache.py
> +    assert cache._taxonomy_path.exists()
Don't access private members. Test like:
```py
assert (empty_cache_path / ".cache" / "nuccore").is_dir()
```
Use `is_dir()`. The `exists()` method is less specific.

2024-03-20 18:53 UTC, igboyes commented on tests/test_ncbi_cache.py
> +    assert list(cache._taxonomy_path.glob("*.json")) != []
Why use glob? The directory should be completely empty of anything.

2024-03-20 18:54 UTC, merged