Taxonomy record parser
virtool/virtool-cli pull request #121
Opened 2024-03-22 21:31 UTC by sygao

2024-03-25 21:29 UTC, igboyes requested changes
* Conflicts with `alpha` need to be resolved before merge
* Look at Deepsource issues.
* Add opening comment for PR so I know what it is doing. I think I get it and seems good to me.

2024-03-25 21:29 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +        return lineage
Use list comprehension.

2024-03-26 00:46 UTC, sygao commented
> * Look at Deepsource issues.

We might want to exclude `PYL-R0201` from test files. I don't think that recommended fix plays well with pytest.

2024-03-27 17:37 UTC, igboyes commented
I think [this PR](https://github.com/virtool/virtool-cli/pull/125) should resolve the problem. We can just ignore in tests.

2024-03-27 17:43 UTC, merged