Add `NCBITaxonomyOtherNames` to handle data from the OtherNames field
virtool/virtool-cli pull request #133
Opened 2024-04-02 20:39 UTC by sygao

- test suite now snapshots `.model_dump` output for cleaner `.ambr` files

2024-04-03 21:24 UTC, igboyes requested changes

2024-04-03 21:24 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +        return NCBITaxonomyOtherNames(**raw)
I wouldn't have expected this to be necessary. Are you sure it is?

2024-04-03 21:24 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +        return int(raw)
This should happen automatically.

https://docs.pydantic.dev/latest/concepts/conversion_table/

2024-04-03 21:24 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +    includes: list[str] = Field([], validation_alias="Includes")
Keep the names as is, apart from converting them consistently to snake case. For example, `EquivalentName` -> `equivalent_name` and `Acronym` -> `acronym`.

I've seen this sort of slight renaming lead to confusion and unexpected behaviour.

2024-04-03 21:24 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +    model_config = ConfigDict(populate_by_name=True)
Aren't the field names always going to match the alias? I see you referring to `lineage_item_clean`, but when would that happen in the wild?

2024-04-03 21:24 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +    names_table: list[dict] = Field([], validation_alias="Name")
What is this for? It is not obvious so it should probably have a docstring.

2024-04-03 22:44 UTC, sygao commented on virtool_cli/ncbi/model.py
> +    names_table: list[dict] = Field([], validation_alias="Name")
This is the weird `Names` field [I mentioned on Linear](https://linear.app/virtool/issue/CLI-45/make-other-names-available-in-ncbitaxonomy#comment-d6dfaf13). We can redact it for now if you'd like.

2024-04-03 23:03 UTC, sygao commented on virtool_cli/ncbi/model.py
> +    model_config = ConfigDict(populate_by_name=True)
`validation_alias` mucks with that behaviour, so unless `ConfigDict` says otherwise, you cannot initialize the model using the actual field name.

It doesn't seem intuitive to me, so when I have to compute `NCBITaxonomy.species` manually, [I use the model field names](https://github.com/virtool/virtool-cli/blob/b978c3a6f39121a2768111d7f43ba69886d85670/virtool_cli/ncbi/model.py#L95) instead of the keys in the XML document.

2024-04-04 17:15 UTC, igboyes reviewed
One more question.

2024-04-04 17:15 UTC, igboyes commented on virtool_cli/ncbi/model.py
> +    model_config = ConfigDict(populate_by_name=True)
After looking more closely at your code, I see why `populate_by_name` is set for `NCBILineage`, but I don't see where it is used for `NCBITaxonomyOtherNames`.

2024-04-04 17:18 UTC, sygao commented on virtool_cli/ncbi/model.py
> +    model_config = ConfigDict(populate_by_name=True)
Ah, you're right. I just put it in preemptively. Will remove.

2024-04-04 17:28 UTC, igboyes approved these changes

2024-04-04 17:29 UTC, merged