NCBIGenbank modifications
virtool/virtool-cli pull request #134
Opened 2024-04-03 17:42 UTC by sygao

- NCBIGenbank validator now rejects sequence data with bad letters
- Downgraded validation failure from an error log to a debug log

2024-04-03 18:40 UTC, igboyes requested changes

2024-04-03 18:40 UTC, igboyes commented on tests/test_ncbi_model.py
> +        NCBIGenbank(**record)
You need to make sure the `ValidationError` actually contains the errors you expect.

2024-04-03 23:25 UTC, sygao commented on tests/test_ncbi_model.py
> +        NCBIGenbank(**record)
I've narrowed the test pass down to errors on the `GBSeq_sequence` field validation. Any errors on other fields should fail the test.

Does it have to match the exact message? The error wording may change in the future.

2024-04-04 16:52 UTC, igboyes approved these changes

2024-04-04 16:54 UTC, merged