Add some return typing
virtool/virtool-cli pull request #147
Opened 2024-04-22 21:25 UTC by sygao

- Add `ref.event_index_cache.EventIndexCache`
- Add `EventSourcedRepo._event_index_cache` and integrate cache and load into default `.get_otu()` operation
- Add `EventSourcedRepo._get_event_index_after_start()`

2024-05-02 18:04 UTC, igboyes requested changes

2024-05-02 19:50 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> +            )
True, this event mostly happens when debugging... 

I do want to handle this problem somehow, but an exception-based solution would be better. `EventCacheException`?

2024-05-02 19:56 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> +    at_event: Annotated[int, Field(ge=1)]
`pydantic.dataclasses` seems to work. Could switch to BaseModel easily if you think it's okay.

2024-05-02 20:44 UTC, igboyes commented on virtool_cli/ref/event_index_cache.py
> +    at_event: Annotated[int, Field(ge=1)]
Ah. I didn't see the import and have not seen `pydantic.dataclasses` used before. Is there a benefit over `BaseModel`?

2024-05-02 20:44 UTC, igboyes commented on virtool_cli/ref/event_index_cache.py
> +            )
Sounds good!

2024-05-02 23:52 UTC, sygao commented
My changes were too aggressive to auto-merge, so I had to merge by hand.

I've uploaded the old branch to my [own fork](https://github.com/sygao/virtool-cli/tree/id-event-cache-old) for now.

2024-05-03 17:18 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> +            self.cache_otu_events(otu_id, event_index[otu_id], last_id=last_id)
I initially thought that the event index was more like a TOC, and the terminology seems to have gotten muddled. I may do some more general renaming to make this all work.

2024-05-03 18:43 UTC, merged