Fix for event indexing bug & minor utility functions/properties
virtool/virtool-cli pull request #150
Opened 2024-05-06 17:33 UTC by sygao

- Fix: Off-by-one error in `Repo._iter_events_from_index()`
- Add: `Repo.index_otus()` returns a `taxid: otu_id` list
- Add: `.accessions` properties for `OTU` and `Isolate`
- Refactor: `NCBIGenbank` now has default values in correct position
- Refactor: Miscellaneous debugging logs

2024-05-07 19:06 UTC, igboyes requested changes

2024-05-07 20:14 UTC, sygao commented on virtool_cli/ref/resources.py
> +        return None
Yes. This PR is one branch separated into a before and after, and the latter commits of this PR have some preparatory work.

2024-05-07 20:43 UTC, sygao commented on virtool_cli/ref/resources.py
> +        return DataType(raw)
Ran into some issues when trying to convert to Pydantic because `DataType` wasn't subclassed. Will test if things hold up with the fix lower down.

2024-05-08 19:10 UTC, igboyes approved these changes

2024-05-08 19:12 UTC, merged