Convenience features for resources: OTUs, isolates and sequences
virtool/virtool-cli pull request #154
Opened 2024-06-10 17:14 UTC by sygao

- Add `EventSourcedRepoOTU.repr_isolate`
- `._eq_()` for `EventSourcedRepoOTU`, `Isolate` and `Sequence`
- Add `exclude_contents` flag to to `OTU` and `Isolate`
- `.isolate_ids` and `.sequence_ids` properties
- rename `test_otu_retrieve.py` to `test_resources.py`

2024-06-12 21:35 UTC, igboyes requested changes

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +        assert isolate._sequences_by_accession == {}
Don't access a private member in test. This will work equally well:
```py
assert isolate.sequences == []
```

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +        isolate = EventSourcedRepoIsolate(
```suggestion
    def test_no_sequences(self)
        """Test that an isolate intializes correctly with no sequences."""
        isolate = EventSourcedRepoIsolate(
```

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +    def test_equivalence(self, taxid, scratch_repo):
This makes more sense in `TestOTU` to me.

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +        assert otu._isolates_by_id == {}
Replicate changes from isolate tests.

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +            assert type(isolate) is EventSourcedRepoIsolate
You are already doing this at line 58.

2024-06-12 21:35 UTC, igboyes commented on tests/ref/test_resources.py
> +        otu_copy = EventSourcedRepoOTU(
I would just use snapshot testing.

2024-06-12 21:35 UTC, igboyes commented on virtool_cli/ref/resources.py
> +        return set(sequence.id for sequence in self.sequences)
```suggestion
        return {sequence.id for sequence in self.sequences}
```

2024-06-12 21:35 UTC, igboyes commented on virtool_cli/ref/resources.py
> +    def __eq__(self, other) -> bool:
* Add type hint for `other`.
* `other` must also be the same type as `self` for this to return `True`.

2024-06-12 21:35 UTC, igboyes commented on virtool_cli/ref/resources.py
>          """Isolates contained in this OTU"""
```suggestion
        """Isolates contained in this OTU."""
```

2024-06-12 21:35 UTC, igboyes commented on virtool_cli/ref/resources.py
> +    def get_sequence_by_accession(self, accession) -> EventSourcedRepoSequence | None:
Type hint.

2024-06-12 22:43 UTC, sygao commented on tests/ref/test_resources.py
> +    def test_equivalence(self, taxid, scratch_repo):
I would like to preserve one equivalence test for each level of resource. The higher resources are dependent on the lower equalities panning out, and I want each equivalence test to be roughly the same.

2024-06-12 22:55 UTC, sygao commented on tests/ref/test_resources.py
> +        otu_copy = EventSourcedRepoOTU(
This IS testing `.__eq__()` specifically, not the contents in of themselves. I'll add a docstring.

2024-06-13 16:58 UTC, igboyes commented on tests/ref/test_resources.py
> +        otu_copy = EventSourcedRepoOTU(
> This IS testing `.__eq__()` specifically, not the contents in of themselves. I'll add a docstring.

OK. I get it now. I think this should be called `test_eq` or `test_equality` then. And yes, docstring please.

2024-06-13 17:58 UTC, merged