Add Snapshots/Read Model
virtool/virtool-cli pull request #158
Opened 2024-06-18 18:25 UTC by sygao

Revision of [PR 152](https://github.com/virtool/virtool-cli/pull/152).

- Add `ref.snapshot.index`
	- Add `.SnapshotIndex`
		- `.id_to_taxid` maps Virtool id to taxid
		- `index_by_taxid`, `.index_by_name` and `.index_by_legacy_id` maps to Virtool id
		- .snapshot() creates a new set of snapshots from a list of `EventSourcedRepoOTU`
	- Add `.OTUKeys` dataclass to hold indexable information

- Add `ref.snapshot.otu`
	- Add `.OTUSnapshot`
		- `OTUSnapshot.load()` returns snapshot data
		- `OTUSnapshot.cache()` writes snapshot data for a whole OTU
	- Add `OTUSnapshotToC`: Loads and writes table of contents data
	- Add `OTUSnapshotDataStore`: Handles the `data` subdirectory, writes isolates and sequences

- Add `ref.snapshot.models`:
	- `OTUSnapshotSequence`, `OTUSnapshotIsolate`, `OTUSnapshotOTU` base models parse, validate and serialize repo data
	- `OTUSnapshotToCIsolate` base model handles table of contents entries for each isolate
	- 	`OTUSnapshotMeta` holds metadata for the OTU, namely `.at_event`

2024-06-18 23:59 UTC, igboyes requested changes

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/utils.py
> +        return IsolateName(type=IsolateNameType(parts[0]), value=parts[1])
When would this be useful?

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +    def index_by_id(self) -> dict[uuid.UUID, int]:
Not used anywhere. The same property on snapshotter is also only referenced here.

2024-06-18 23:59 UTC, igboyes commented on tests/snapshot/test_models.py
> +    shutil.rmtree(scratch_repo.cache_path / "snapshot")
This happens as part of `scratch_repo` already.

2024-06-18 23:59 UTC, igboyes commented on tests/snapshot/test_models.py
> +        ],
I'm not sure what the point of parametrization is here. There is only one permutation.

2024-06-18 23:59 UTC, igboyes commented on tests/snapshot/test_otu_snapshot.py
> +    shutil.rmtree(scratch_repo.cache_path / "snapshot")
Shouldn't be necessary. Already done in `scratch_repo`.

2024-06-18 23:59 UTC, igboyes commented on tests/snapshot/test_otu_snapshot.py
> +            assert otu_snapshotter.path / f"{filestem}.json"
What does this do?

2024-06-18 23:59 UTC, igboyes commented on tests/snapshot/test_otu_snapshot.py
> +        data_dir = otu_snapshotter.path / "data"
```suggestion
        path = otu_snapshotter.path / "data"
```

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/otu.py
> +        otu = repo.get_otu_by_taxid(taxid)
The index check should be encapsulated in `get_otu_by_taxid`.

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +    def otu_ids(self) -> set:
Not used anywhere. Remove.

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +    def index_by_id(self) -> dict[uuid.UUID, int]:
Not used anywhere. Remove. Exposing the index is a leaky abstraction.

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +    def index_by_taxid(self) -> dict[int, uuid.UUID]:
This is used in only one place and I don't think it should be used there.
Remove. Exposing the index is a leaky abstraction.

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +        self._snapshotter.cache_isolate_to_otu(otu_id, isolate, at_event=self.last_id)
At this point, we have the ID of the last event that affected the OTU.

I think it would be simpler, more robust, and less code if snapshotter only ever wrote the whole OTU.

1. Get current OTU representation.
2. Write isolate events.
3. Apply events to current OTU represention from step 1.
4. Write complete new snapshot for whole OTU.

This method can be reused for any other current event types or ones left to come. It also means each of these `cache_***` methods does not need to be updated if the shape of the resources changes.

This approach also ensures snapshots are only generated from event data. I am not comfortable with the way the snapshot is written from the method parameters instead the result of applying the events to the repo.

2024-06-18 23:59 UTC, igboyes commented on virtool_cli/ref/repo.py
> +            path.mkdir()
Use `exists_ok`.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

2024-06-19 00:14 UTC, sygao commented on virtool_cli/ref/utils.py
> +        return IsolateName(type=IsolateNameType(parts[0]), value=parts[1])
Getting `IsolateName` back from a table of contents key. I don't necessarily have to do it that way, though.

2024-06-19 17:31 UTC, sygao commented on virtool_cli/ref/repo.py
> +        self._snapshotter.cache_isolate_to_otu(otu_id, isolate, at_event=self.last_id)
Okay, got it. I've put a step into `.create_sequence()` and `.create_isolate()` that retrieves the OTU from the event store every time there is a new write. I'll work on the efficiency problem later

2024-06-20 17:30 UTC, merged