refactor: simplify event index
virtool/virtool-cli pull request #161
Opened 2024-06-21 22:02 UTC by igboyes

* Remove duplicate, conflicting, or unused fixtures.
* Fix conflicting repo fixture paths.
* Remove unused repo and event index methods.

2024-06-21 23:22 UTC, sygao requested changes

2024-06-21 23:22 UTC, sygao commented on tests/test_add_bulk.py
We're still to need tests that simulate building and and querying a reasonably-sized repo from the interface. Ferreting out the more difficult bugs in `Snapshotter` and `EventIndex` will probably require larger tests of this nature.

2024-06-21 23:22 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> +    def get(self, otu_id: UUID) -> EventIndexItem | None:
`.get()` is a little too stripped down for my comfort. `.load()` appears to return an entire dictionary, after all.

I think we should still reference OTU in the method name.

2024-06-24 17:36 UTC, igboyes commented on virtool_cli/ref/event_index_cache.py
> +    def get(self, otu_id: UUID) -> EventIndexItem | None:
I'm not sure what you mean. What is it missing?

2024-06-24 17:59 UTC, igboyes commented on tests/test_add_bulk.py
I agree, but I don't think the rest of the code works well enough right now to do a good job of it.

This test module did not include the complete isolate information and it turned out it was glossing over ordering issues and isolates being binned inconsistently and incorrectly.

Once the units are rock solid, let's do it.

2024-06-24 18:10 UTC, igboyes commented on virtool_cli/ref/event_index_cache.py
> -    def sort_events(self):
I've added a test to make sure unsorted event IDs are sorted on write.

2024-06-24 18:12 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> +    def get(self, otu_id: UUID) -> EventIndexItem | None:
`.get()`/`.set()` deal with single OTUs, `.load()` deals with a batch of them. The scale of the operation isn't adequately implied in the method names.

2024-06-24 18:17 UTC, sygao commented on virtool_cli/ref/event_index_cache.py
> -    def sort_events(self):
I put this in to deal with some bugs that popped up while I was developing the thing, but you're right. I've probably put in too many hacky failsafes as stopgaps.

2024-06-24 18:27 UTC, merged