Add merge-refs command
virtool/virtool-cli pull request #59
Opened 2021-12-06 19:39 UTC by eroberts9789

Add command to merge contents of a source and target reference with user input.

Match up OTUs from input refs by their taxids and write isolates to output dir without repeats.

Cache results as each isolate is checked. Allow user to resume in-progress merge.

Add tests.

2021-12-07 18:13 UTC, igboyes requested changes
Good bones and comparison logic but,

1. Can you not reuse existing test data instead of adding more to the repository?
2. Be consistent and use double quotes.
3. Fix formatting of hardcoded test data. It is hard to look at.

Can you sell me on storing and passing paths everywhere?

It seems to me that this:
```
tests/files/target_ref/src/a/abutilon_brazil_virus/un404hxp/isolate.json
```
Could be better expressed as:
```
("target", "abutilon_brazil_virus", "un404hxp")
```

2021-12-08 19:37 UTC, igboyes requested changes

2021-12-08 19:37 UTC, igboyes commented on tests/test_merge_refs.py
> +                            IsolateInfo(ref="target", otu_name="abutilon_brazil_virus", id="un404hxp")]}
This is how this should look to be readable. Please update other similar blocks accordingly.
```suggestion
expected = {
    "unknown": [
        IsolateInfo(ref="source", otu_name="abutilon_brazil_virus", id="un404hxp"),
        IsolateInfo(ref="target", otu_name="abutilon_brazil_virus", id="un404hxp")
    ]
}
```

2021-12-08 19:37 UTC, igboyes commented on virtool_cli/merge_refs.py
> +                isolate_path.mkdir()
Check docs for `mkdir()`. You can avoid `try..except` using one of its arguments.

There are other blocks where this applies. Fix them too.

2021-12-08 19:37 UTC, igboyes commented on virtool_cli/merge_refs.py
> +            isolate_path = Path(result["otu_path"]) / isolate["id"]
Isn't `result["otu_path"]` already a `Path` object?

2021-12-08 19:37 UTC, igboyes commented on virtool_cli/merge_refs.py
> +            continue
You could just make the isolate paths with `mkdir` and use its helpful kwargs to make this a lot simpler.

2021-12-08 19:37 UTC, igboyes commented on virtool_cli/merge_refs.py
> +    return Path(isolate_path)
Convert all paths to `Path` objects at the beginning of the command and use `/` instead of string interpolation.

2021-12-08 19:56 UTC, igboyes commented
Example of interactive CLI output:
```
Are these isolates the same?

    • Source - Isolate Q767 (13892)
        • <accession> | <definition> | Length=12345
        • <accession> | <definition> | Length=421
    • Target - Isolate Q767 (23901)
        • <accession> | <definition> | Length=12345
        • <accession> | <definition> | Length=12345
```
Use colour to distinguish or symbols to distinguish.

Do a similar output for choosing first, second, neither, or both. Use a numbered list and ask the user to choose a number.

Make sure this merges in sequences.

2021-12-08 21:03 UTC, eroberts9789 commented on virtool_cli/merge_refs.py
> +            isolate_path = Path(result["otu_path"]) / isolate["id"]
Yes, but it has to be stored as a string because the results objects are stored in the cache and `Path` types aren't JSON serializable

2021-12-13 22:33 UTC, igboyes approved these changes

2021-12-13 22:33 UTC, merged

2021-12-16 22:03 UTC, igboyes commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/virtool/virtool-cli/releases/tag/0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: